apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
         - name: webapp
           image: kamil38490/pipeline-demo
           imagePullPolicy: Always
           ports:
           - containerPort :80
