apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: kamil38490/pipeline-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
